'use client'

import { useState, useCallback } from 'react'
import dynamic from 'next/dynamic'
import { Canvas } from '@react-three/fiber'
import { Suspense } from 'react'
import { motion } from 'framer-motion'
import GlassPanel from '@/components/ui/GlassPanel'
import { COLORS } from '@/lib/constants'
import { LAYERS } from '@/components/three/SphinxScene'

const SphinxScene = dynamic(
  () => import('@/components/three/SphinxScene'),
  { ssr: false }
)

// ── Cryptographic operations data ─────────────────────────────────────────────

interface CryptoOp {
  id: string
  title: string
  subtitle: string
  description: string
  color: string
}

const CRYPTO_OPS: CryptoOp[] = [
  {
    id: 'ecdh',
    title: 'ECDH Key Exchange',
    subtitle: 'Elliptic-Curve Diffie-Hellman',
    description:
      "Each node has a long-term Curve25519 public key. The sender performs ECDH with each hop's key to derive a shared secret — never transmitted over the wire.",
    color: COLORS.neonBlue,
  },
  {
    id: 'kdf',
    title: 'KDF Derivation',
    subtitle: 'HKDF-SHA256',
    description:
      'From the ECDH shared secret, HKDF-SHA256 derives two keys: a stream cipher key (Kenc) and a MAC key (Kmac). Each hop gets unique keys — zero key reuse.',
    color: COLORS.purple,
  },
  {
    id: 'stream',
    title: 'Stream Cipher',
    subtitle: 'ChaCha20',
    description:
      'The header bytes are XORed with a keystream generated by ChaCha20 using Kenc. This reveals the next-hop address and peels one onion layer.',
    color: '#00e5ff',
  },
  {
    id: 'mac',
    title: 'MAC Verification',
    subtitle: 'Poly1305 Authentication',
    description:
      'Before any decryption is acted upon, the Poly1305 MAC is verified with Kmac. If it fails, the packet is silently dropped — no error signals.',
    color: '#a855f7',
  },
  {
    id: 'surb',
    title: 'SURB Generation',
    subtitle: 'Single-Use Reply Block',
    description:
      "A pre-built encrypted reply path embedded in the packet. The service can send a reply to the client without ever learning the client's real address.",
    color: COLORS.green,
  },
]

// ── Layer operations per hop ──────────────────────────────────────────────────

const LAYER_OPS: string[][] = [
  ['Header decryption (AES-256-GCM)', 'MAC verification (HMAC-SHA256)', 'Routing info extracted', 'Packet forwarded'],
  ['ECDH key derivation', 'KDF → Kenc + Kmac', 'Layer 2 header decrypted', 'Next-hop resolved'],
  ['ChaCha20 stream decryption', 'Integrity check passed', 'Payload wrapper removed', 'Blinding factor applied'],
  ['Inner header decrypted', 'Ephemeral key destroyed', 'Final routing computed', 'SURB processed'],
  ['Final payload exposed', 'All layers consumed', 'Application data delivered', 'Forward secrecy ensured'],
]

const MOCK_KEYS = [
  '0x3f9a2b1c...e84d7f62',
  '0xa1b2c3d4...9e8f7a6b',
  '0x5c4d3e2f...1a0b9c8d',
  '0x7e6f5d4c...3b2a1908',
  '0x9d8c7b6a...5e4f3021',
]

// ── Forward secrecy timeline ───────────────────────────────────────────────────

interface FsStep {
  hop: string
  action: string
  destroy: string
}

const FS_STEPS: FsStep[] = [
  { hop: 'Guard Node', action: 'Derives Kenc₀, Kmac₀ via ECDH', destroy: 'Ephemeral key α destroyed' },
  { hop: 'Mix Node 1', action: 'Derives Kenc₁, Kmac₁ via ECDH', destroy: 'Ephemeral key β destroyed' },
  { hop: 'Mix Node 2', action: 'Derives Kenc₂, Kmac₂ via ECDH', destroy: 'Ephemeral key γ destroyed' },
  { hop: 'Exit Node', action: 'Derives Kenc₃, Kmac₃ via ECDH', destroy: 'Ephemeral key δ destroyed' },
  { hop: 'Destination', action: 'Payload delivered in plaintext', destroy: 'Session key θ destroyed' },
]

// ── Animated packet hero ───────────────────────────────────────────────────────

function HeroPacketViz() {
  const ringData = [
    { scale: 2.2, color: COLORS.neonBlue, label: 'Header', dir: 1, dur: 12 },
    { scale: 1.75, color: COLORS.purple, label: 'Routing', dir: -1, dur: 16 },
    { scale: 1.35, color: '#00e5ff', label: 'Wrapper', dir: 1, dur: 20 },
    { scale: 1.0, color: '#a855f7', label: 'Inner', dir: -1, dur: 14 },
    { scale: 0.65, color: COLORS.green, label: 'Payload', dir: 1, dur: 18 },
  ]

  return (
    <div className="relative flex items-center justify-center" style={{ height: 220 }}>
      {ringData.map((r, i) => (
        <motion.div
          key={i}
          className="absolute rounded-full border"
          style={{
            width: r.scale * 80,
            height: r.scale * 80,
            borderColor: `${r.color}50`,
            background: `radial-gradient(circle, ${r.color}08, transparent 70%)`,
            boxShadow: `0 0 ${20 + i * 4}px ${r.color}20`,
          }}
          animate={{ rotate: r.dir * 360 }}
          transition={{ duration: r.dur, repeat: Infinity, ease: 'linear' }}
        >
          <div
            className="absolute text-[8px] font-mono"
            style={{
              top: '50%',
              left: '50%',
              transform: `translate(-50%, -50%) translateX(${r.scale * 38}px)`,
              color: r.color,
              whiteSpace: 'nowrap',
            }}
          >
            {r.label}
          </div>
        </motion.div>
      ))}
      <motion.div
        className="rounded-full flex items-center justify-center text-[10px] font-mono z-10"
        style={{
          width: 40,
          height: 40,
          background: `radial-gradient(circle, ${COLORS.green}30, ${COLORS.green}08)`,
          border: `1px solid ${COLORS.green}50`,
          color: COLORS.green,
          boxShadow: `0 0 20px ${COLORS.green}40`,
          position: 'relative',
        }}
        animate={{ scale: [1, 1.1, 1] }}
        transition={{ duration: 2, repeat: Infinity }}
      >
        PKT
      </motion.div>
    </div>
  )
}

// ── Layer inspector panel ──────────────────────────────────────────────────────

interface LayerInspectorProps {
  peeledCount: number
  onPeel: () => void
  onReset: () => void
  peeling: boolean
}

function LayerInspector({ peeledCount, onPeel, onReset, peeling }: LayerInspectorProps) {
  const remaining = 5 - peeledCount
  const currentLayerIndex = peeledCount
  const currentLayer = LAYERS[currentLayerIndex]
  const ops = LAYER_OPS[currentLayerIndex] ?? []
  const mockKey = MOCK_KEYS[currentLayerIndex] ?? '0x000000...000000'
  const progress = (peeledCount / 5) * 100

  return (
    <div className="flex flex-col gap-4 h-full">
      {/* Header */}
      <GlassPanel accentColor={currentLayer?.color ?? COLORS.neonBlue} padding="1.25rem">
        <div className="flex items-center justify-between mb-3">
          <span
            className="text-xs uppercase tracking-widest"
            style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-jetbrains-mono)' }}
          >
            Layer Inspector
          </span>
          <span
            className="text-sm font-bold"
            style={{ color: currentLayer?.color ?? COLORS.neonBlue, fontFamily: 'var(--font-jetbrains-mono)' }}
          >
            {remaining > 0 ? `LAYER ${peeledCount + 1} of 5` : 'FULLY PEELED'}
          </span>
        </div>

        {currentLayer && remaining > 0 ? (
          <>
            <h3
              className="text-xl font-bold mb-1"
              style={{ color: currentLayer.color, fontFamily: 'var(--font-display)' }}
            >
              {currentLayer.name}
            </h3>
            <p className="text-sm" style={{ color: 'var(--text-muted)' }}>
              {currentLayer.description}
            </p>
          </>
        ) : (
          <p className="text-sm" style={{ color: COLORS.green }}>
            All Sphinx layers have been peeled. The inner payload is now exposed.
          </p>
        )}

        <div className="mt-4">
          <div className="flex justify-between text-xs mb-1" style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-jetbrains-mono)' }}>
            <span>Layers peeled</span>
            <span>{peeledCount}/5</span>
          </div>
          <div className="h-1.5 rounded-full" style={{ background: 'rgba(255,255,255,0.06)' }}>
            <motion.div
              className="h-full rounded-full"
              style={{ background: currentLayer?.color ?? COLORS.green }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.5, ease: 'easeOut' }}
            />
          </div>
        </div>
      </GlassPanel>

      {currentLayer && remaining > 0 && (
        <GlassPanel accentColor={COLORS.purple} padding="1rem">
          <p className="text-xs uppercase tracking-widest mb-2" style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-jetbrains-mono)' }}>
            Ephemeral Key
          </p>
          <code
            className="text-sm break-all"
            style={{ color: COLORS.purple, fontFamily: 'var(--font-jetbrains-mono)' }}
          >
            {mockKey}
          </code>
        </GlassPanel>
      )}

      {remaining > 0 && (
        <GlassPanel accentColor={COLORS.neonBlue} padding="1rem" className="flex-1">
          <p className="text-xs uppercase tracking-widest mb-3" style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-jetbrains-mono)' }}>
            Operations at this hop
          </p>
          <ul className="space-y-2">
            {ops.map((op, i) => (
              <motion.li
                key={op}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.08 }}
                className="flex items-center gap-2 text-sm"
                style={{ color: 'var(--text-secondary)' }}
              >
                <span style={{ color: COLORS.green }}>&#10003;</span>
                <span style={{ fontFamily: 'var(--font-jetbrains-mono)', fontSize: 12 }}>{op}</span>
              </motion.li>
            ))}
          </ul>
        </GlassPanel>
      )}

      <div className="flex gap-3">
        <button
          onClick={onPeel}
          disabled={peeling || remaining === 0}
          className="flex-1 py-3 rounded-xl text-sm font-bold uppercase tracking-widest transition-all duration-200 disabled:opacity-40"
          style={{
            background: remaining > 0 ? `${COLORS.neonBlue}18` : 'rgba(255,255,255,0.04)',
            border: `1px solid ${remaining > 0 ? COLORS.neonBlue : 'rgba(255,255,255,0.1)'}40`,
            color: remaining > 0 ? COLORS.neonBlue : 'var(--text-muted)',
            fontFamily: 'var(--font-jetbrains-mono)',
          }}
        >
          {peeling ? 'Peeling...' : remaining === 0 ? 'All Peeled' : 'Peel Layer'}
        </button>
        <button
          onClick={onReset}
          className="px-5 py-3 rounded-xl text-sm font-bold uppercase tracking-widest transition-all duration-200"
          style={{
            background: 'rgba(255,255,255,0.04)',
            border: '1px solid rgba(255,255,255,0.1)',
            color: 'var(--text-muted)',
            fontFamily: 'var(--font-jetbrains-mono)',
          }}
        >
          Reset
        </button>
      </div>
    </div>
  )
}

// ── Crypto ops card ────────────────────────────────────────────────────────────

interface CryptoCardProps {
  op: CryptoOp
  index: number
}

const CRYPTO_ICONS: Record<string, React.ReactNode> = {
  ecdh: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className="w-7 h-7">
      <circle cx="7" cy="12" r="3" />
      <circle cx="17" cy="12" r="3" />
      <path d="M10 12h4" strokeDasharray="2 2" />
    </svg>
  ),
  kdf: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className="w-7 h-7">
      <path d="M12 3v4M12 17v4M3 12h4M17 12h4" />
      <circle cx="12" cy="12" r="4" />
    </svg>
  ),
  stream: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className="w-7 h-7">
      <rect x="3" y="8" width="18" height="8" rx="2" />
      <path d="M7 12h2M11 12h2M15 12h2" />
    </svg>
  ),
  mac: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className="w-7 h-7">
      <path d="M12 2L4 6v6c0 5.5 3.5 10.7 8 12 4.5-1.3 8-6.5 8-12V6z" />
      <path d="M9 12l2 2 4-4" />
    </svg>
  ),
  surb: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className="w-7 h-7">
      <path d="M20 12V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2h6" />
      <path d="M16 19l2 2 4-4" />
      <path d="M8 10h8M8 14h5" />
    </svg>
  ),
}

function CryptoCard({ op, index }: CryptoCardProps) {
  const [hovered, setHovered] = useState(false)

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ delay: index * 0.1, duration: 0.5 }}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      className="relative rounded-2xl overflow-hidden flex-shrink-0 cursor-default"
      style={{
        width: 240,
        background: 'linear-gradient(180deg, rgba(15,18,22,0.92) 0%, rgba(15,18,22,0.5) 100%)',
        border: `1px solid ${hovered ? op.color + '50' : op.color + '18'}`,
        backdropFilter: 'blur(20px)',
        padding: '1.5rem',
        transition: 'border-color 0.3s, box-shadow 0.3s',
        boxShadow: hovered ? `0 0 30px ${op.color}20` : 'none',
      }}
    >
      <div
        className="pointer-events-none absolute top-0 left-0 right-0 h-px"
        style={{
          background: `linear-gradient(90deg, transparent, ${op.color}${hovered ? '60' : '30'}, transparent)`,
          transition: 'opacity 0.3s',
        }}
      />
      <div
        className="mb-4 w-12 h-12 rounded-xl flex items-center justify-center"
        style={{
          background: `${op.color}12`,
          border: `1px solid ${op.color}30`,
          color: op.color,
        }}
      >
        {CRYPTO_ICONS[op.id]}
      </div>
      <p className="label-caps text-[10px] text-primary mb-1" style={{ color: op.color }}>
        {op.subtitle}
      </p>
      <h4 className="text-base font-bold mb-2" style={{ color: 'var(--text-secondary)', fontFamily: 'var(--font-display)' }}>
        {op.title}
      </h4>
      <p className="text-xs leading-relaxed" style={{ color: 'var(--text-muted)' }}>
        {op.description}
      </p>
    </motion.div>
  )
}

// ── Main page ──────────────────────────────────────────────────────────────────

export default function SphinxPage() {
  const [peeledCount, setPeeledCount] = useState(0)
  const [peeling, setPeeling] = useState(false)

  const handlePeel = useCallback(() => {
    if (peeling || peeledCount >= 5) return
    setPeeling(true)
  }, [peeling, peeledCount])

  const handlePeelComplete = useCallback(() => {
    setPeeledCount((c) => Math.min(c + 1, 5))
    setPeeling(false)
  }, [])

  const handleReset = useCallback(() => {
    setPeeledCount(0)
    setPeeling(false)
  }, [])

  return (
    <main style={{ minHeight: '100vh' }}>

      {/* ── Section 1: Hero ── */}
      <section
        className="relative flex flex-col items-center justify-center text-center overflow-hidden"
        style={{ minHeight: '100vh' }}
      >
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            background: `radial-gradient(ellipse 70% 60% at 50% 50%, ${COLORS.purple}10, transparent 70%)`,
          }}
        />
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="relative z-10 px-6"
        >
          <div className="label-caps text-[10px] text-primary mb-3">
            Sphinx Protocol
          </div>
          <h1
            className="font-display text-[44px] md:text-[72px] font-semibold leading-[1.05] tracking-tight mb-6"
            style={{
              background: `linear-gradient(135deg, ${COLORS.purple}, ${COLORS.neonBlue})`,
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
              filter: `drop-shadow(0 0 40px ${COLORS.purple}50)`,
            }}
          >
            SPHINX PACKET EXPLORER
          </h1>
          <p
            className="text-base sm:text-lg max-w-2xl mx-auto mb-10"
            style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-display)', lineHeight: 1.8 }}
          >
            The Sphinx packet format wraps data in layered onion encryption.
            Each mix node peels exactly one layer — revealing only the next hop,
            never the origin or destination.
          </p>
          <HeroPacketViz />
          <motion.div
            className="mt-12"
            animate={{ y: [0, 8, 0] }}
            transition={{ duration: 2, repeat: Infinity }}
          >
            <div className="flex flex-col items-center gap-2">
              <span className="text-xs" style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-jetbrains-mono)' }}>
                scroll to explore
              </span>
              <div className="w-px h-8" style={{ background: `linear-gradient(to bottom, ${COLORS.purple}60, transparent)` }} />
            </div>
          </motion.div>
        </motion.div>
      </section>

      {/* ── Section 2: Packet Explorer ── */}
      <section
        id="explorer"
        className="relative"
        style={{ minHeight: '100vh', padding: '80px 0' }}
      >
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            background: `radial-gradient(ellipse 80% 50% at 30% 50%, ${COLORS.neonBlue}08, transparent 70%)`,
          }}
        />
        <div className="max-w-7xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <div className="label-caps text-[10px] text-primary mb-3">
              Interactive Explorer
            </div>
            <h2 className="font-display text-3xl md:text-4xl font-semibold text-text-primary">
              Packet Layer Explorer
            </h2>
          </motion.div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="relative rounded-2xl overflow-hidden"
              style={{
                height: 520,
                background: 'rgba(5,5,8,0.8)',
                border: '1px solid rgba(139,148,158,0.18)',
              }}
            >
              <Suspense
                fallback={
                  <div className="flex h-full items-center justify-center" style={{ color: 'var(--text-muted)' }}>
                    Loading 3D Scene...
                  </div>
                }
              >
                <Canvas
                  camera={{ position: [0, 0, 7], fov: 50 }}
                  style={{ background: 'transparent' }}
                  gl={{ antialias: true, alpha: true }}
                >
                  <SphinxScene
                    peeledCount={peeledCount}
                    peeling={peeling}
                    onPeelComplete={handlePeelComplete}
                  />
                </Canvas>
              </Suspense>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              style={{ minHeight: 520 }}
            >
              <LayerInspector
                peeledCount={peeledCount}
                onPeel={handlePeel}
                onReset={handleReset}
                peeling={peeling}
              />
            </motion.div>
          </div>
        </div>
      </section>

      {/* ── Section 3: Cryptographic Operations ── */}
      <section
        className="relative py-24 overflow-hidden border-t border-border bg-surface-low/30"
      >
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            background: `radial-gradient(ellipse 60% 50% at 50% 50%, ${COLORS.purple}08, transparent)`,
          }}
        />
        <div className="relative max-w-7xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <div className="label-caps text-[10px] text-primary mb-3">
              Cryptographic Operations
            </div>
            <h2 className="font-display text-3xl md:text-4xl font-semibold text-text-primary">
              Operations Per Hop
            </h2>
            <p className="mt-4 text-sm max-w-xl mx-auto" style={{ color: 'var(--text-muted)' }}>
              Every mix node performs these operations in order — any failure causes silent packet drop.
            </p>
          </motion.div>

          <div className="overflow-x-auto pb-4">
            <div className="flex gap-5" style={{ minWidth: 'max-content', paddingBottom: 8 }}>
              {CRYPTO_OPS.map((op, i) => (
                <CryptoCard key={op.id} op={op} index={i} />
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Section 4: Forward Secrecy ── */}
      <section className="relative py-24">
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            background: `radial-gradient(ellipse 50% 60% at 70% 50%, ${COLORS.green}06, transparent)`,
          }}
        />
        <div className="relative max-w-4xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <div className="label-caps text-[10px] text-primary mb-3">
              Security Properties
            </div>
            <h2 className="font-display text-3xl md:text-4xl font-semibold text-text-primary">
              Forward Secrecy
            </h2>
            <p className="mt-4 text-sm max-w-xl mx-auto" style={{ color: 'var(--text-muted)' }}>
              Ephemeral keys are destroyed immediately after use. Compromising a node
              after the fact reveals nothing about past sessions.
            </p>
          </motion.div>

          <div className="relative">
            <div
              className="absolute left-6 top-0 bottom-0 w-px"
              style={{ background: `linear-gradient(to bottom, ${COLORS.green}40, transparent)` }}
            />
            <div className="space-y-8">
              {FS_STEPS.map((step, i) => (
                <motion.div
                  key={step.hop}
                  initial={{ opacity: 0, x: 30 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true, margin: '-60px' }}
                  transition={{ delay: i * 0.12, duration: 0.5 }}
                  className="flex gap-6 items-start pl-16 relative"
                >
                  <div
                    className="absolute left-0 w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0"
                    style={{
                      background: `${COLORS.green}12`,
                      border: `2px solid ${COLORS.green}50`,
                      color: COLORS.green,
                      fontFamily: 'var(--font-jetbrains-mono)',
                      fontSize: 12,
                      fontWeight: 700,
                    }}
                  >
                    {i + 1}
                  </div>
                  <GlassPanel accentColor={COLORS.green} padding="1.25rem" className="flex-1">
                    <div className="flex flex-col sm:flex-row sm:items-center gap-4">
                      <div className="flex-1">
                        <p className="text-xs uppercase tracking-widest mb-1" style={{ color: COLORS.green, fontFamily: 'var(--font-jetbrains-mono)' }}>
                          {step.hop}
                        </p>
                        <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                          {step.action}
                        </p>
                      </div>
                      <div
                        className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs"
                        style={{
                          background: 'rgba(255,51,102,0.08)',
                          border: '1px solid rgba(255,51,102,0.25)',
                          color: COLORS.red,
                          fontFamily: 'var(--font-jetbrains-mono)',
                          whiteSpace: 'nowrap',
                        }}
                      >
                        <span>&#128293;</span>
                        {step.destroy}
                      </div>
                    </div>
                  </GlassPanel>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </main>
  )
}
